#!/bin/sh
# ===========================================================================
# run_all.sh -- build the program and run all three examples end to end.
#
#     ./run_all.sh              run every example
#     ./run_all.sh c50929       run one example by name
#
# POSIX sh: works under bash, dash or zsh on Linux and macOS.
#
# Nothing needs to be supplied.  For each scene the program is run against its
# BCWS fire-perimeter hint, then the six-panel plate, the agreement figure and
# the blink GIF are produced.
#
# Threads.  Every stage runs one POSIX worker per CPU by default, taking job
# indices from a shared counter: one job per row of the neighbour table, per
# block of pixels, and per value of K in the sweep.  Set THREADS to override,
# e.g.  THREADS=64 ./run_all.sh
#
# Decimation.  n_skip is chosen automatically so that about BUDGET points are
# retained (20000 by default): n_skip = ceil(n_dedup / BUDGET).  Either can be
# set here --- NSKIP=8 fixes the stride outright, BUDGET=60000 asks for more
# points and lets the stride follow.  More points means finer classes and a
# larger neighbour table: it grows as n_points x k_max.
#
# Cost.  The neighbour table is n_points x k_max entries of 12 bytes, so at the
# default k_max of 10000 expect a little over 2 GB of RAM and a cache file of
# the same size per scene.  Lower it with KMAX=5000 if that is too much.  The sweep visits
# K = k_step, 2 k_step, ... and stops early once the best match stops
# improving, so it rarely runs to k_max.  The deduplication and the neighbour
# table are memoised beside each image and keyed on a checksum of the binary,
# so a second run of the same scene skips both; rm data/*.kgc_* reclaims the
# space.
# ===========================================================================

set -e

CXX=${CXX:-c++}
CXXFLAGS=${CXXFLAGS:--O3 -std=c++11 -pthread}
PYTHON=${PYTHON:-python3}
OUT=${OUT:-out}
THREADS=${THREADS:-}
KMAX=${KMAX:-}
KSTEP=${KSTEP:-}
NSKIP=${NSKIP:-}
BUDGET=${BUDGET:-}
PLATES=${PLATES:-plates}
GIFS=${GIFS:-gifs}

# ---------------------------------------------------------------------------
# checks
# ---------------------------------------------------------------------------
if ! command -v "$CXX" >/dev/null 2>&1; then
    printf 'error: no C++ compiler found (tried "%s").\n' "$CXX" >&2
    printf 'Set CXX, e.g.  CXX=g++-13 ./run_all.sh\n' >&2
    exit 1
fi
have_python=1
if ! command -v "$PYTHON" >/dev/null 2>&1; then
    have_python=0
    printf 'warning: %s not found; the clustering will run but no figures\n' "$PYTHON" >&2
    printf '         will be produced.  Set PYTHON to override.\n' >&2
fi

# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------
printf '\n== build ==\n'
# shellcheck disable=SC2086
$CXX $CXXFLAGS kgc.cpp -o kgc
printf 'built ./kgc\n'

mkdir -p "$OUT" "$PLATES" "$GIFS"

# ---------------------------------------------------------------------------
# one example: tag, scene stem, human-readable title
# ---------------------------------------------------------------------------
run_one() {
    tag=$1
    stem=$2
    title=$3

    img="data/${stem}_mrap_prepost.bin"
    hint="data/${stem}_hint_bcws_perimeter.bin"
    pre="${OUT}/${tag}"

    if [ ! -f "$img" ] || [ ! -f "$hint" ]; then
        printf 'skipping %s: %s or %s is missing\n' "$tag" "$img" "$hint" >&2
        return 0
    fi

    printf '\n== %s ==\n' "$title"
    set -- "$img" --hint "$hint" --out "$pre"
    [ -n "$THREADS" ] && set -- "$@" --threads "$THREADS"
    [ -n "$KMAX" ]    && set -- "$@" --kmax "$KMAX"
    [ -n "$KSTEP" ]   && set -- "$@" --kstep "$KSTEP"
    [ -n "$NSKIP" ]   && set -- "$@" --nskip "$NSKIP"
    [ -n "$BUDGET" ]  && set -- "$@" --budget-points "$BUDGET"
    ./kgc "$@"

    if [ "$have_python" -eq 1 ]; then
        "$PYTHON" plates.py "$img" "$pre" "$PLATES" "$tag" "$title"
        "$PYTHON" gifs.py   "$img" "$pre" "$GIFS"   "$tag" "$title"
    fi

    # A LaTeX run summary, so the report shows this run's numbers rather than
    # numbers baked in when it was written.
    if [ -f "${pre}_params.txt" ]; then
        mkdir -p latex
        {
            printf '%% generated by run_all.sh -- do not edit\n'
            printf '\\begin{tabular}{ll}\n\\toprule\n'
            sed 's/#.*//' "${pre}_params.txt" | awk -F= '
                NF >= 2 {
                    k = $1; v = $2
                    gsub(/^[ \t]+|[ \t]+$/, "", k)
                    gsub(/^[ \t]+|[ \t]+$/, "", v)
                    if (v == "") next
                    gsub(/_/, "\\_", k); gsub(/_/, "\\_", v)
                    gsub(/%/, "\\%", v)
                    printf "\\texttt{%s} & %s \\\\\n", k, v
                }'
            printf '\\bottomrule\n\\end{tabular}\n'
        } > "latex/results_${tag}.tex"
    fi
}

# ---------------------------------------------------------------------------
# the three examples
# ---------------------------------------------------------------------------
want=${1:-all}

for tag in c50929 c10467 k41351; do
    [ "$want" = all ] || [ "$want" = "$tag" ] || continue
    case $tag in
        c50929) run_one c50929 C50929 "C50929, BCWS perimeter hint" ;;
        c10467) run_one c10467 C10467 "C10467, BCWS perimeter hint" ;;
        k41351) run_one k41351 K41351 "K41351, BCWS perimeter hint" ;;
    esac
done

# ---------------------------------------------------------------------------
# summary
# ---------------------------------------------------------------------------
printf '\n== done ==\n'
printf '  %s/plate_*.png        six-panel summary per example\n' "$PLATES"
printf '  %s/agreement_*.png    agreement and evidence per example\n' "$PLATES"
printf '  %s/blink_*.gif        imagery alternating with the class\n' "$GIFS"
printf '  %s/*_klevels.csv      one row per neighbourhood size K\n' "$OUT"
printf '  %s/*_selected.bin     6-band ENVI product per example\n' "$OUT"
printf '  latex/results_*.tex       run summary, included by the report\n'
printf '\nTo run a single example:   ./run_all.sh c10467\n'
printf 'To use a different hint:   ./kgc data/C50929_mrap_prepost.bin \\\n'
printf '                                --hint data/C50929_hint_redwins_post.bin \\\n'
printf '                                --out out/c50929_rw\n'
printf 'Report (needs pdflatex):   make -C latex\n'
