python ../../py/class_merge.py BROADLEAF_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py CCUTBL_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py CONIFER_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py EXPOSED_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py HERB_GRAS_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py MIXED_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py RiversSP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py SHRUB_SP.tif_project_4x.bin_sub.bin 1 
python ../../py/class_merge.py WATERSP.tif_project_4x.bin_sub.bin 1 
